### ISSUE TITLE
How to compile scheme code into elf?

### ISSUE THREAD

**Issue by evilbinary** [weinholt/machine-code#7]
How to compile scheme code into elf?

**Comment by weinholt** [comment]
Sorry, I completely missed this question.

There is nothing really special in the machine-code project to help with this, there is just an assembler that could use if you already have the assembly output from a compiler. A nice introduction to making such a compiler is An Incremental Approach to Compiler Construction: http://scheme2006.cs.uchicago.edu/11-ghuloum.pdf
And a nice way to write the compiler passes in a more structured way, the nanopass framework: http://nanopass.org/.
